### ISSUE TITLE
Missing Assets

### ISSUE THREAD

**Issue by Sighman6** [ClemensX/ShadedPath12#3]
Hi,
Nice work so far.
It would be nice if you provided the assets that you use in your tests. The data directory is missing...

**Comment by ClemensX** [comment]
Hi,
I tend to not include most assets in git repo. But you can find many of them in the release zip files. Please go to Code Tab then click Releases. Some assets I will never be able to provide due to copyright issues.
I will release another version in some days where I use a default texture for missing assets so that the applications can still run with missing textures. For the mesh data (.b files) please also expect updated versions in the next release.

**Comment by ClemensX** [comment]
Introduced pak file support with release 0.1.2. The provided pak file contains all the textures, so there should be no more 'missing texture' errors.
